---
- name: Stop Services
  hosts: all #DB
  become: true
  become_method: sudo
  ignore_errors: true        #Don't stop in case of errors
  tasks: 
  - name: Stop r1soft on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="7")
    systemd:
      name: sbm-agent
      state: stopped
    ignore_errors: true

  - name: Stop r1soft on CentOS 6
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="6")
    service:
      name: cdp-agent
      state: stopped
    ignore_errors: true

  - name: Stop FileBeat on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="7")
    systemd:
      name: filebeat
      state: stopped
    ignore_errors: true

  - name: Stop NRPE on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="7")
    systemd:
      name: nrpe
      state: stopped
    ignore_errors: true

  - name: Stop MariaDB on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="7")
    systemd:
      name: mariadb
      state: stopped
    ignore_errors: true


