---
- name: Task 1
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks: 
  - name: Create instance
    ec2:
      instance_type: t2.micro
      count: 1
      region: eu-west-2



  