---
- name: Task 1
  hosts: all
  become: true
  become_method: sudo
  user: centos
  ignore_errors: true
  tasks: 

  - name: Launch instance
    ec2:
      key_name: ansible
      group: sg-03d8a01093b306b00
      instance_type: t2.medium
      image: ami-0affd4508a5d2481b
      wait: true
      region: us-east-1
      vpc_subnet_id: subnet-0edaa5ef44008af6c
    register: ec2

  - name: Start Apache  on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="7")
    systemd:
      name: httpd
      state: started

  - name: Start MariaDB on CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_major_version =="7")
    systemd:
      name: httpd
      state: started
    ignore_errors: true

  - name: Create a user
    user:
      name: bob

     
    
  