  - name: Install MariaDB package
    package: 
      name: mariadb-server
      state: installed      

  - name: Install MySQL-python package
    package: 
      name: MySQL-python
      state: installed   

  - name: Install PyMySQL package
    package: 
      name: PyMySQL 
      state: installed  
      
 generate_ssh_key: yes
ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

      - name: Add User 
    mysql_user: 
      name: bob
      state: present