  - name: Install MariaDB package
    package: 
      name: mariadb-server
      state: installed      

  - name: Install MySQL-python package
    package: 
      name: MySQL-python
      state: installed   

  - name: Install PyMySQL package
    package: 
      name: PyMySQL 
      state: installed  
      
  - name: Add User 
    mysql_user: 
      name: bob
      state: present