  - name: Install MariaDB package
    package: 
      name: mariadb-server
      state: installed      

  - name: Install MySQL-python package
    package: 
      name: MySQL-python
      state: installed   

  - name: Install PyMySQL package
    package: 
      name: PyMySQL 
      state: installed  
      
 generate_ssh_key: yes
ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

      - name: Add User 
    mysql_user: 
      name: bob
      state: present

---
- name: Task 1
  hosts: all
  become: true
  become_method: sudo
  user: centos
  tasks: 
  - name: Create instance
    ec2:
      key_name: VPC Task Bastion Public Key
      instance_type: t2.micro
      image: ami-0affd4508a5d2481b
      group: SSH
      count: 1
      region: us-east-1
      vpc_subnet_id: subnet-13123b69
      assign_public_ip: yes